### PR TITLE
Added javascript ES6 template string interpolation syntax coloring

### PR DESCRIPTION
**Pull request by cmbankester**
- Color punctuation red
- Unset string color for contents of interpolation inside a template string

### CODE REVIEW

**Comment by bassu** [comment]
@cbankester Thanks for this!

**Comment by cmbankester** [comment]
@bassu Necessity is the mother of invention. :) Thanks for merging that in.

**Comment by cmbankester** [comment]
@bassu Would you mind bumping the version so Atom picks up the update?

**Comment by bassu** [comment]
:smile:

**Pull request merged**
